from trait and enum
okamotonr/hack_assembler pull request #1
Opened 2020-09-07 03:46 UTC by okamotonr

from trait

AsmLine from struct to enum

2020-09-07 05:01 UTC, yawara requested changes

2020-09-07 05:01 UTC, yawara commented on src/parser.rs
>              let nimonick: &str = nimonick.unwrap();
ここでunwrapするとpanicするので、以下の選択肢がある。

1. Fromの代わりにTryFromにする
2. From<Option<&str>をやめてFrom<&str>にする

From自体をTryFromにするかFrom<&str>をimpl

2020-09-08 09:11 UTC, okamotonr commented
fix #2

2020-09-08 22:10 UTC, yawara approved these changes

2020-09-09 06:37 UTC, merged